// Chapter 8: Circles. Text follows ASD-STE100: short sentences, active voice, one idea each.
// Inline math uses $...$ (KaTeX). Questions: set 'check' (in-lesson), 'chapter' (full solutions), 'supplemental' (answer only), 'bank' (exam only).
import type { ChapterContent } from '../types';

export const ch8: ChapterContent = {
chapter: { id: 'ch8', number: 8, title: 'Circles', sections: [
  { id: '8-1', title: 'Parts of a Circle', kind: 'lesson', built: true, summary: 'A circle is the set of all points at one distance from a center. A radius goes from the center to the circle. A chord connects two points on the circle. A diameter is a chord through the center.', formula: 'd = 2r' },
  { id: '8-2', title: 'Central Angles and Arcs', kind: 'lesson', built: true, parts: ['Central Angles', 'Arcs'], summary: 'A central angle has its vertex at the center. The arc it cuts off has the same measure as the angle. A minor arc is less than 180°. A major arc is more than 180°.', formula: 'm\\widehat{AB} = m\\angle AOB' },
  { id: '8-3', title: 'Some Common Sense Stuff', kind: 'lesson', built: true, summary: 'The arcs of a full circle add to 360°. A diameter cuts a circle into two semicircles of 180° each. Equal central angles cut off equal arcs in the same circle.', formula: 'm\\widehat{AB} + m\\widehat{BC} = m\\widehat{ABC}' },
  { id: '8-4', title: 'Arcs and Inscribed Angles', kind: 'lesson', built: true, summary: 'An inscribed angle has its vertex on the circle. Its measure is half the arc it intercepts.', formula: 'm\\angle ABC = \\tfrac{1}{2}\\, m\\widehat{AC}' },
  { id: '8-5', title: 'Angles Formed by Chords, Secants, and Tangents', kind: 'lesson', built: true, summary: 'Two chords that cross inside a circle make angles equal to half the sum of the two intercepted arcs. Two secants from an outside point make an angle equal to half the difference of the arcs.', formula: 'm\\angle 1 = \\tfrac{1}{2}(m\\widehat{AB} + m\\widehat{CD})' },
  { id: '8-6', title: 'Arcs and Chords', kind: 'lesson', built: true, summary: 'Equal chords cut off equal arcs. A diameter that is perpendicular to a chord bisects the chord and its arc.', formula: '\\overline{AB} \\cong \\overline{CD} \\iff \\widehat{AB} \\cong \\widehat{CD}' },
  { id: '8-7', title: 'Segments of Chords, Secants, and Tangents', kind: 'lesson', built: true, summary: 'When two chords cross, the products of their segments are equal. A tangent squared equals the external secant segment times the whole secant.', formula: 'a \\cdot b = c \\cdot d' },
  { id: '8-8', title: 'Arc Lengths and Sectors', kind: 'lesson', built: true, parts: ['Arc Length', 'Sectors of a Circle'], summary: 'Arc length is a fraction of the circumference. Sector area is the same fraction of the circle area. The fraction is the central angle over 360°.', formula: 's = \\frac{\\theta}{360^\\circ} \\cdot 2\\pi r, \\quad A = \\frac{\\theta}{360^\\circ} \\cdot \\pi r^2' },
  { id: '8-p', title: 'Chapter Problems', kind: 'problems' },
  { id: '8-s', title: 'Supplemental Chapter Problems', kind: 'supplemental' },
]},

lessons: {
'8-1': {
  diagram: 'circle',
  intro: [
    'A circle is the set of all points in a plane at one distance from a fixed point. The fixed point is the center. The distance is the radius. We name a circle by its center, so circle $O$ has center $O$.',
    'Some segments and lines have special names. A chord joins two points on the circle. A diameter is a chord through the center, so $d = 2r$. A secant is a line that cuts the circle at two points. A tangent is a line that touches the circle at one point.',
    'The diagram shows a circle with two sliders. Drag the radius slider and watch the circumference and the area change. Drag the central angle slider and watch the chord, the arc, and the sector. The readouts show each formula with the numbers filled in.',
    'A tangent meets the circle at the point of tangency. The radius to that point is perpendicular to the tangent. This gives a right angle, so you can use the Pythagorean Theorem.',
  ],
  definitions: [
    { term: 'Center', text: 'The fixed point inside a circle. Every point on the circle is the same distance from it.' },
    { term: 'Radius and diameter', text: 'A radius goes from the center to the circle. A diameter is a chord through the center. $d = 2r$.' },
    { term: 'Chord', text: 'A segment with both endpoints on the circle.' },
    { term: 'Secant and tangent', text: 'A secant is a line that cuts the circle at two points. A tangent is a line that touches the circle at exactly one point.' },
    { term: 'Point of tangency', text: 'The one point where a tangent touches the circle.' },
    { term: 'Concentric and congruent circles', text: 'Concentric circles share the same center. Congruent circles have the same radius.' },
  ],
  formulas: [
    { label: 'Diameter', tex: 'd = 2r' },
    { label: 'Tangent and radius', tex: '\\overline{OT} \\perp \\overleftrightarrow{PT} \\text{ at } T' },
  ],
  theorems: ['8.16'],
  examples: [
    { title: 'Example 1 — Diameter from radius', given: 'The radius of circle $O$ is $7.5$. Find the diameter.', steps: [
      'A diameter is two radii end to end.',
      '$d = 2r = 2 \\cdot 7.5 = 15$',
    ]},
    { title: 'Example 2 — Concentric circles', given: 'Two concentric circles have radii $3$ and $8$. A radius of the large circle crosses both circles. Find the length of the part between the circles.', steps: [
      'Both circles have the same center $O$.',
      'The part between the circles is the large radius minus the small radius.',
      '$8 - 3 = 5$',
    ]},
    { title: 'Example 3 — Tangent and radius', given: 'Line $PT$ is tangent to circle $O$ at $T$. $OT = 6$ and $PT = 8$. Find $OP$.', steps: [
      'The radius $\\overline{OT}$ is perpendicular to the tangent at $T$ (Theorem 8.16).',
      'Triangle $OTP$ has a right angle at $T$.',
      'Use the Pythagorean Theorem: $OP^2 = 6^2 + 8^2 = 100$.',
      '$OP = 10$',
    ]},
  ],
  checks: ['c8-1-1', 'c8-1-2', 'c8-1-3'],
},
'8-2': {
  diagram: 'inscribed',
  intro: [
    'A central angle has its vertex at the center of the circle. Its sides are two radii. The angle cuts the circle into two arcs.',
    'The smaller arc is the minor arc. Its measure equals the measure of the central angle. The larger arc is the major arc. Its measure is $360^\\circ$ minus the minor arc. An arc of exactly $180^\\circ$ is a semicircle.',
    'We name a minor arc with its two endpoints, for example $\\widehat{AC}$. We name a major arc or a semicircle with three letters. The middle letter is a point on the arc, for example $\\widehat{ABC}$.',
    'In the diagram, turn on the central angle $\\angle AOC$. Drag $A$ and $C$ around the circle. Watch that the arc $AC$ always equals the central angle. Move $B$ to the other side of the circle. The readout now shows the major arc. The minor arc and the major arc add to $360^\\circ$.',
  ],
  definitions: [
    { term: 'Central angle', text: 'An angle with its vertex at the center of a circle and two radii as sides.' },
    { term: 'Minor arc', text: 'An arc less than $180^\\circ$. Its measure equals its central angle.' },
    { term: 'Major arc', text: 'An arc greater than $180^\\circ$. Its measure is $360^\\circ$ minus the minor arc.' },
    { term: 'Semicircle', text: 'An arc of exactly $180^\\circ$. Its endpoints are the ends of a diameter.' },
  ],
  formulas: [
    { label: 'Central Angle Theorem', tex: 'm\\widehat{AC} = m\\angle AOC' },
    { label: 'Major arc', tex: 'm\\widehat{ABC} = 360^\\circ - m\\widehat{AC}' },
  ],
  theorems: ['8.2'],
  examples: [
    { title: 'Example 1 — Arc from central angle', given: 'Central angle $\\angle AOB$ measures $80^\\circ$. Find $m\\widehat{AB}$.', steps: [
      'Use the Central Angle Theorem.',
      'The minor arc equals the central angle.',
      '$m\\widehat{AB} = 80^\\circ$',
    ]},
    { title: 'Example 2 — Major arc', given: 'Minor arc $AB$ measures $80^\\circ$. Point $C$ is on the major arc. Find $m\\widehat{ACB}$.', steps: [
      'The two arcs make the whole circle.',
      '$m\\widehat{ACB} = 360^\\circ - 80^\\circ = 280^\\circ$',
    ]},
    { title: 'Example 3 — Name the arcs', given: 'In circle $O$, $m\\angle POQ = 110^\\circ$. Point $R$ is on the circle outside the angle. Name and measure both arcs from $P$ to $Q$.', steps: [
      'The minor arc is $\\widehat{PQ}$. It equals the central angle, $110^\\circ$.',
      'The major arc passes through $R$, so we name it $\\widehat{PRQ}$.',
      '$m\\widehat{PRQ} = 360^\\circ - 110^\\circ = 250^\\circ$',
    ]},
  ],
  checks: ['c8-2-1', 'c8-2-2', 'c8-2-3'],
},
'8-3': {
  diagram: 'inscribed',
  intro: [
    'The arcs of a whole circle add to $360^\\circ$. If a point $B$ lies on arc $AC$, the two small arcs add to the big arc. This is the Arc Addition Postulate. It works the same way as the Angle Addition Postulate.',
    'Congruent central angles cut off congruent arcs. This is true in one circle or in congruent circles. A diameter makes two central angles of $180^\\circ$ each. So a diameter cuts the circle into two semicircles.',
    'In the diagram, turn on the central angle $\\angle AOC$. Drag $A$ and $C$ and watch the arc $AC$ match the central angle. Then move $B$ to the other side of the circle. The readout switches to the major arc. Add the minor arc and the major arc. The sum is always $360^\\circ$.',
  ],
  definitions: [
    { term: 'Arc addition', text: 'If $B$ is on $\\widehat{AC}$, then $m\\widehat{AB} + m\\widehat{BC} = m\\widehat{AC}$.' },
    { term: 'Congruent arcs', text: 'Arcs in the same circle, or in congruent circles, with the same measure.' },
    { term: 'Diameter and semicircles', text: 'A diameter cuts the circle into two arcs of $180^\\circ$. Each one is a semicircle.' },
  ],
  formulas: [
    { label: 'Arc Addition Postulate', tex: 'm\\widehat{AB} + m\\widehat{BC} = m\\widehat{ABC}' },
    { label: 'Whole circle', tex: 'm\\widehat{AB} + m\\widehat{BC} + m\\widehat{CA} = 360^\\circ' },
  ],
  theorems: ['8.1', '8.3', '8.4'],
  examples: [
    { title: 'Example 1 — Add two arcs', given: 'Point $B$ is on $\\widehat{AC}$. $m\\widehat{AB} = 40^\\circ$ and $m\\widehat{BC} = 95^\\circ$. Find $m\\widehat{ABC}$.', steps: [
      'Use the Arc Addition Postulate.',
      '$m\\widehat{ABC} = 40^\\circ + 95^\\circ = 135^\\circ$',
    ]},
    { title: 'Example 2 — The third arc', given: 'Points $A$, $B$, and $C$ cut a circle into three arcs. $m\\widehat{AB} = 120^\\circ$ and $m\\widehat{BC} = 150^\\circ$. Find $m\\widehat{CA}$.', steps: [
      'The three arcs make the whole circle, so they add to $360^\\circ$.',
      '$m\\widehat{CA} = 360^\\circ - 120^\\circ - 150^\\circ = 90^\\circ$',
    ]},
    { title: 'Example 3 — Diameter and semicircle', given: '$\\overline{AB}$ is a diameter of circle $O$. Point $C$ is on the circle. $m\\widehat{AC} = 70^\\circ$. Find $m\\widehat{CB}$.', steps: [
      'A diameter makes a semicircle, so $m\\widehat{ACB} = 180^\\circ$ (Theorem 8.4).',
      'Use the Arc Addition Postulate: $m\\widehat{AC} + m\\widehat{CB} = 180^\\circ$.',
      '$m\\widehat{CB} = 180^\\circ - 70^\\circ = 110^\\circ$',
    ]},
  ],
  checks: ['c8-3-1', 'c8-3-2', 'c8-3-3'],
},
'8-4': {
  diagram: 'inscribed',
  video: 'inscribed-angles',
  videoTitle: 'Why an inscribed angle is half its arc',
  intro: [
    'An inscribed angle has its vertex on the circle. Its two sides are chords.',
    'The angle cuts off an arc. We call this arc the intercepted arc. The arc is on the far side of the vertex.',
    'Drag the three points in the diagram. Watch the angle and the arc. The angle is always half the arc.',
  ],
  definitions: [
    { term: 'Inscribed angle', text: 'An angle with its vertex on the circle and with chords as sides.' },
    { term: 'Intercepted arc', text: 'The arc that lies in the interior of an inscribed angle.' },
  ],
  formulas: [
    { label: 'Inscribed Angle Theorem', tex: 'm\\angle ABC = \\tfrac{1}{2}\\, m\\widehat{AC}' },
    { label: 'Angle in a semicircle', tex: 'm\\widehat{AC} = 180^\\circ \\implies m\\angle ABC = 90^\\circ' },
  ],
  theorems: ['8.5', '8.6', '8.7', '8.8'],
  examples: [
    { title: 'Example 1 — Find the angle', given: 'Arc $AC$ measures $110^\\circ$. Find $m\\angle ABC$.', steps: [
      'Use the Inscribed Angle Theorem.',
      '$m\\angle ABC = \\tfrac{1}{2} \\cdot 110^\\circ$',
      '$m\\angle ABC = 55^\\circ$',
    ]},
    { title: 'Example 2 — Find the arc', given: 'Inscribed angle $\\angle PQR$ measures $38^\\circ$. Find $m\\widehat{PR}$.', steps: [
      'The arc is two times the angle.',
      '$m\\widehat{PR} = 2 \\cdot 38^\\circ = 76^\\circ$',
    ]},
    { title: 'Example 3 — Diameter as a side', given: '$\\overline{AC}$ is a diameter. $m\\angle A = 32^\\circ$. Find $m\\angle C$.', steps: [
      'Arc $AC$ is a semicircle, so $m\\widehat{AC} = 180^\\circ$.',
      'Angle $B$ intercepts this arc. $m\\angle B = 90^\\circ$.',
      'The angles of a triangle add to $180^\\circ$.',
      '$m\\angle C = 180^\\circ - 90^\\circ - 32^\\circ = 58^\\circ$',
    ]},
  ],
  checks: ['c8-4-1', 'c8-4-2', 'c8-4-3'],
},
'8-5': {
  intro: [
    'Chords, secants, and tangents make angles with the circle. The vertex can be inside the circle, on the circle, or outside the circle. Each position has its own rule. Every rule uses the arcs that the angle cuts off.',
    'Vertex inside: two chords cross inside the circle. The angle is half the sum of the two arcs it intercepts. Use the arc inside the angle and the arc inside its vertical angle.',
    'Vertex outside: two secants, a secant and a tangent, or two tangents meet at a point outside the circle. The angle is half the difference of the far arc and the near arc. The same rule works for all three cases.',
    'Vertex on the circle: a tangent and a chord meet at the point of tangency. The angle is half the arc inside it. This is like the Inscribed Angle Theorem.',
  ],
  definitions: [
    { term: 'Chord-chord angle', text: 'An angle made by two chords that cross inside the circle.' },
    { term: 'Secant-secant angle', text: 'An angle made by two secants that meet at a point outside the circle.' },
    { term: 'Tangent-chord angle', text: 'An angle made by a tangent and a chord at the point of tangency.' },
    { term: 'Far arc and near arc', text: 'For an outside vertex, the far arc is the larger intercepted arc. The near arc is the smaller one.' },
  ],
  formulas: [
    { label: 'Vertex inside (two chords)', tex: 'm\\angle 1 = \\tfrac{1}{2}(m\\widehat{AB} + m\\widehat{CD})' },
    { label: 'Vertex outside (secants or tangents)', tex: 'm\\angle P = \\tfrac{1}{2}(\\text{far arc} - \\text{near arc})' },
    { label: 'Vertex on the circle (tangent and chord)', tex: 'm\\angle 1 = \\tfrac{1}{2}\\, m\\widehat{AB}' },
  ],
  theorems: ['8.9', '8.10', '8.17'],
  examples: [
    { title: 'Example 1 — Two chords', given: 'Chords $\\overline{AC}$ and $\\overline{BD}$ cross at $E$. $m\\widehat{AB} = 60^\\circ$ and $m\\widehat{CD} = 100^\\circ$. Find $m\\angle AEB$.', steps: [
      'Angle $AEB$ intercepts $\\widehat{AB}$. Its vertical angle intercepts $\\widehat{CD}$.',
      'Use Theorem 8.9. The angle is half the sum of the two arcs.',
      '$m\\angle AEB = \\tfrac{1}{2}(60^\\circ + 100^\\circ) = 80^\\circ$',
    ]},
    { title: 'Example 2 — Two secants', given: 'Two secants from point $P$ outside the circle intercept arcs of $110^\\circ$ and $30^\\circ$. Find $m\\angle P$.', steps: [
      'The far arc is $110^\\circ$. The near arc is $30^\\circ$.',
      'Use Theorem 8.10. The angle is half the difference.',
      '$m\\angle P = \\tfrac{1}{2}(110^\\circ - 30^\\circ) = 40^\\circ$',
    ]},
    { title: 'Example 3 — Tangent and chord', given: 'A tangent and a chord meet at point $A$ on the circle. The arc inside the angle measures $150^\\circ$. Find the angle.', steps: [
      'Use Theorem 8.17. The angle is half the arc inside it.',
      '$\\tfrac{1}{2}(150^\\circ) = 75^\\circ$',
    ]},
  ],
  checks: ['c8-5-1', 'c8-5-2', 'c8-5-3'],
},
'8-6': {
  intro: [
    'A chord and its arc belong together. Congruent chords cut off congruent arcs. Congruent arcs have congruent chords. This is true in one circle or in congruent circles.',
    'A diameter that is perpendicular to a chord bisects the chord. It also bisects the arc of the chord. This makes a right triangle with a radius as the hypotenuse. So you can use the Pythagorean Theorem to find the half-chord or the distance to the center.',
    'The distance from the center to a chord is the perpendicular segment. Two chords at the same distance from the center are congruent. A longer chord is closer to the center. A diameter is the longest chord and passes through the center.',
  ],
  definitions: [
    { term: 'Arc of a chord', text: 'The minor arc with the same endpoints as the chord.' },
    { term: 'Bisect a chord', text: 'To cut the chord into two congruent parts at its midpoint.' },
    { term: 'Distance from the center to a chord', text: 'The length of the perpendicular segment from the center to the chord.' },
  ],
  formulas: [
    { label: 'Congruent chords and arcs', tex: '\\overline{AB} \\cong \\overline{CD} \\iff \\widehat{AB} \\cong \\widehat{CD}' },
    { label: 'Half-chord and distance to the center', tex: '\\left(\\tfrac{1}{2}AB\\right)^2 + d^2 = r^2' },
  ],
  theorems: ['8.18', '8.11', '8.19'],
  examples: [
    { title: 'Example 1 — Perpendicular diameter', given: 'Circle $O$ has radius $13$. A diameter is perpendicular to chord $\\overline{AB}$ at $M$. $AB = 24$. Find $OM$.', steps: [
      'The diameter bisects the chord (Theorem 8.11), so $AM = 12$.',
      'Triangle $OMA$ has a right angle at $M$ and hypotenuse $OA = 13$.',
      '$OM^2 = 13^2 - 12^2 = 169 - 144 = 25$',
      '$OM = 5$',
    ]},
    { title: 'Example 2 — Congruent chords', given: 'In circle $O$, $\\overline{AB} \\cong \\overline{CD}$. $m\\widehat{AB} = 70^\\circ$. Find $m\\widehat{CD}$.', steps: [
      'Congruent chords cut off congruent arcs (Theorem 8.18).',
      '$m\\widehat{CD} = 70^\\circ$',
    ]},
    { title: 'Example 3 — Chords at the same distance', given: 'Chords $\\overline{PQ}$ and $\\overline{RS}$ are both $4$ units from the center of a circle with radius $5$. Find $RS$.', steps: [
      'Chords at the same distance from the center are congruent (Theorem 8.19), so $PQ = RS$.',
      'The perpendicular from the center bisects $\\overline{RS}$. Half of $RS$ is a leg of a right triangle with hypotenuse $5$ and other leg $4$.',
      '$\\left(\\tfrac{1}{2}RS\\right)^2 = 5^2 - 4^2 = 9$, so $\\tfrac{1}{2}RS = 3$.',
      '$RS = 6$',
    ]},
  ],
  checks: ['c8-6-1', 'c8-6-2', 'c8-6-3'],
},
'8-7': {
  intro: [
    'When two lines cut a circle, the pieces have lengths that fit together in products. Two chords that cross inside the circle make four segments. The product of the two parts of one chord equals the product of the two parts of the other.',
    'A secant from an outside point has two lengths. The whole secant goes from the outside point to the far side of the circle. The external segment goes from the outside point to the near side. For two secants from the same point, whole times external is the same for both.',
    'A tangent from an outside point has one length. For a tangent and a secant from the same point, the tangent squared equals the whole secant times its external segment.',
  ],
  definitions: [
    { term: 'Segments of a chord', text: 'The two parts of a chord on each side of the point where another chord crosses it.' },
    { term: 'Whole secant', text: 'The segment from an outside point to the far point where the secant leaves the circle.' },
    { term: 'External segment', text: 'The part of a secant from the outside point to the near point on the circle.' },
    { term: 'Tangent segment', text: 'The segment from an outside point to the point of tangency.' },
  ],
  formulas: [
    { label: 'Two chords', tex: 'a \\cdot b = c \\cdot d' },
    { label: 'Two secants (whole times external)', tex: 'PB \\cdot PA = PD \\cdot PC' },
    { label: 'Tangent and secant', tex: 'PT^2 = PB \\cdot PA' },
  ],
  theorems: ['8.12', '8.20', '8.13'],
  examples: [
    { title: 'Example 1 — Two chords', given: 'Chords $\\overline{AB}$ and $\\overline{CD}$ cross at $E$. $AE = 4$, $EB = 6$, and $CE = 3$. Find $ED$.', steps: [
      'Use Theorem 8.12: $AE \\cdot EB = CE \\cdot ED$.',
      '$4 \\cdot 6 = 3 \\cdot ED$',
      '$24 = 3 \\cdot ED$, so $ED = 8$',
    ]},
    { title: 'Example 2 — Two secants', given: 'Two secants start at $P$. The first has external segment $5$ and whole length $12$. The second has external segment $4$. Find its whole length $x$.', steps: [
      'Use Theorem 8.20: whole times external is equal for both secants.',
      '$12 \\cdot 5 = x \\cdot 4$',
      '$60 = 4x$, so $x = 15$',
    ]},
    { title: 'Example 3 — Tangent and secant', given: 'From point $P$, a tangent touches the circle at $T$. A secant from $P$ has external segment $3$ and whole length $12$. Find $PT$.', steps: [
      'Use Theorem 8.13: $PT^2 = \\text{whole} \\cdot \\text{external}$.',
      '$PT^2 = 12 \\cdot 3 = 36$',
      '$PT = 6$',
    ]},
  ],
  checks: ['c8-7-1', 'c8-7-2', 'c8-7-3'],
},
'8-8': {
  diagram: 'circle',
  intro: [
    'An arc is part of the circle. Its length is part of the circumference. The fraction is the central angle over $360^\\circ$. So arc length $= \\frac{\\theta}{360^\\circ} \\cdot 2\\pi r$.',
    'A sector is a slice of the circle. Two radii and an arc bound it. Its area is the same fraction of the circle area. So sector area $= \\frac{\\theta}{360^\\circ} \\cdot \\pi r^2$.',
    'Drag the radius slider in the diagram. Watch the circumference and the area change. Then drag the central angle slider. Watch the arc length and the sector area grow with the angle. The readouts show each formula with the numbers filled in.',
    'In this book, use $\\pi \\approx 3.14$ when a problem asks for a number. Round at the end, not in the middle.',
  ],
  definitions: [
    { term: 'Arc length', text: 'The distance along an arc. It is a fraction of the circumference.' },
    { term: 'Sector', text: 'The region bounded by two radii and the arc between them.' },
    { term: 'Central angle of a sector', text: 'The angle at the center between the two radii of the sector. We call it $\\theta$.' },
  ],
  formulas: [
    { label: 'Circumference', tex: 'C = 2\\pi r' },
    { label: 'Area of a circle', tex: 'A = \\pi r^2' },
    { label: 'Arc length', tex: 's = \\frac{\\theta}{360^\\circ} \\cdot 2\\pi r' },
    { label: 'Sector area', tex: 'A = \\frac{\\theta}{360^\\circ} \\cdot \\pi r^2' },
  ],
  theorems: ['8.14', '8.15'],
  examples: [
    { title: 'Example 1 — Arc length', given: 'A circle has radius $5$. A central angle of $72^\\circ$ cuts off an arc. Find the arc length. Use $\\pi \\approx 3.14$.', steps: [
      'The fraction of the circle is $\\frac{72}{360} = \\frac{1}{5}$.',
      'The circumference is $2\\pi r = 2(3.14)(5) = 31.4$.',
      'Arc length $= \\tfrac{1}{5}(31.4) = 6.28$',
    ]},
    { title: 'Example 2 — Sector area', given: 'A circle has radius $10$. A sector has a central angle of $36^\\circ$. Find its area. Use $\\pi \\approx 3.14$.', steps: [
      'The fraction of the circle is $\\frac{36}{360} = \\frac{1}{10}$.',
      'The circle area is $\\pi r^2 = 3.14 \\cdot 100 = 314$.',
      'Sector area $= \\tfrac{1}{10}(314) = 31.4$',
    ]},
    { title: 'Example 3 — Find the angle', given: 'A circle has radius $8$. An arc has length $4\\pi$. Find the central angle.', steps: [
      'The circumference is $2\\pi(8) = 16\\pi$.',
      'The fraction is $\\frac{4\\pi}{16\\pi} = \\frac{1}{4}$.',
      'The angle is $\\tfrac{1}{4}(360^\\circ) = 90^\\circ$',
    ]},
  ],
  checks: ['c8-8-1', 'c8-8-2', 'c8-8-3'],
},
},

questions: [
  { id: 'c8-4-1', chapter: 'ch8', section: '8-4', set: 'check', type: 'diagram', figure: { kind: 'inscribed', arc: 96 }, prompt: 'Arc $AC$ measures $96^\\circ$. Find $m\\angle ABC$.', answer: 48, tolerance: 0.5, unit: '°',
    solution: ['An inscribed angle is half its intercepted arc.', '$m\\angle ABC = \\tfrac{1}{2}(96^\\circ) = 48^\\circ$'] },
  { id: 'c8-4-2', chapter: 'ch8', section: '8-4', set: 'check', type: 'mc', prompt: 'Two inscribed angles intercept the same arc. Which statement is true?', choices: ['They are supplementary.', 'They are congruent.', 'They add to $90^\\circ$.', 'The larger one is twice the smaller one.'], answer: 1,
    solution: ['Each angle is half the same arc.', 'Half of one number is one value. So the angles are equal.'] },
  { id: 'c8-4-3', chapter: 'ch8', section: '8-4', set: 'check', type: 'numeric', prompt: '$\\overline{XZ}$ is a diameter. Point $Y$ is on the circle. Find $m\\angle XYZ$.', answer: 90, tolerance: 0.5, unit: '°',
    solution: ['A diameter cuts off a semicircle of $180^\\circ$.', 'The inscribed angle is half of $180^\\circ$, which is $90^\\circ$.'] },
  // ---- 9-1 checks
  { id: 'p8-1', chapter: 'ch8', section: '8-4', set: 'chapter', type: 'diagram', figure: { kind: 'inscribed', arc: 140 }, prompt: 'Arc $AC$ measures $140^\\circ$. Find $m\\angle ABC$.', answer: 70, tolerance: 0.5, unit: '°',
    solution: ['Identify the inscribed angle. The vertex $B$ is on the circle.', 'Apply Theorem 8.5: $m\\angle ABC = \\tfrac{1}{2} m\\widehat{AC}$.', '$m\\angle ABC = \\tfrac{1}{2}(140^\\circ) = 70^\\circ$'] },
  { id: 'p8-2', chapter: 'ch8', section: '8-2', set: 'chapter', type: 'numeric', prompt: 'A central angle measures $72^\\circ$. Find the measure of its major arc.', answer: 288, tolerance: 0.5, unit: '°',
    solution: ['The minor arc equals the central angle: $72^\\circ$.', 'The full circle is $360^\\circ$.', 'Major arc $= 360^\\circ - 72^\\circ = 288^\\circ$'] },
  { id: 'p8-3', chapter: 'ch8', section: '8-8', set: 'chapter', type: 'diagram', figure: { kind: 'sector', r: 6, angle: 60 }, prompt: 'A circle has radius 6. A sector has a central angle of $60^\\circ$. Find the arc length. Use $\\pi \\approx 3.14$.', answer: 6.28, tolerance: 0.05,
    solution: ['The fraction of the circle is $\\frac{60}{360} = \\frac{1}{6}$.', 'The circumference is $2\\pi r = 12\\pi$.', 'Arc length $= \\tfrac{1}{6}(12\\pi) = 2\\pi \\approx 6.28$'] },
  { id: 'p8-4', chapter: 'ch8', section: '8-5', set: 'chapter', type: 'mc', prompt: 'Two chords cross inside a circle. The intercepted arcs measure $80^\\circ$ and $40^\\circ$. Find the angle between the chords.', choices: ['$20^\\circ$', '$40^\\circ$', '$60^\\circ$', '$120^\\circ$'], answer: 2,
    solution: ['Use the chord-chord angle theorem.', 'The angle is half the sum of the arcs.', '$\\tfrac{1}{2}(80^\\circ + 40^\\circ) = 60^\\circ$'] },
  // ---- Chapter 8 supplemental (answers only)
  { id: 's8-1', chapter: 'ch8', section: '8-4', set: 'supplemental', type: 'numeric', prompt: 'An inscribed angle measures $41^\\circ$. Find its intercepted arc.', answer: 82, tolerance: 0.5, unit: '°' },
  { id: 's8-2', chapter: 'ch8', section: '8-7', set: 'supplemental', type: 'numeric', prompt: 'Two chords cross. One chord has segments 3 and 8. The other has a segment of 4. Find the other segment.', answer: 6, tolerance: 0.05 },
  { id: 's8-3', chapter: 'ch8', section: '8-8', set: 'supplemental', type: 'numeric', prompt: 'A sector of a circle with radius 10 has a central angle of $90^\\circ$. Find its area. Use $\\pi \\approx 3.14$.', answer: 78.5, tolerance: 0.3 },
  { id: 's8-4', chapter: 'ch8', section: '8-6', set: 'supplemental', type: 'mc', prompt: 'A diameter is perpendicular to a chord of length 16. How long is each half of the chord?', choices: ['4', '8', '16', '32'], answer: 1 },

  // ---- Chapter 9 problems
  { id: 'b8-1', chapter: 'ch8', section: '8-4', set: 'bank', type: 'numeric', prompt: 'A quadrilateral is inscribed in a circle. One angle is $115^\\circ$. Find the opposite angle.', answer: 65, tolerance: 0.5, unit: '°', solution: ['Opposite angles of an inscribed quadrilateral are supplementary.', '$180^\\circ - 115^\\circ = 65^\\circ$'] },
  { id: 'b8-2', chapter: 'ch8', section: '8-1', set: 'bank', type: 'mc', prompt: 'A circle has diameter 14. Find the radius.', choices: ['28', '14', '7', '3.5'], answer: 2, solution: ['$r = d \\div 2 = 7$'] },
  // ---- Chapter 8 lesson checks (8-1, 8-2, 8-3, 8-5, 8-6, 8-7, 8-8)
  { id: 'c8-1-1', chapter: 'ch8', section: '8-1', set: 'check', type: 'diagram', figure: { kind: 'circle', r: 9 }, prompt: 'The radius of circle $O$ is $9$. Find the diameter.', answer: 18, tolerance: 0.5,
    solution: ['A diameter is two radii end to end.', '$d = 2r = 2 \\cdot 9 = 18$'] },
  { id: 'c8-1-2', chapter: 'ch8', section: '8-1', set: 'check', type: 'mc', prompt: 'Which one always passes through the center of the circle?', choices: ['Chord', 'Diameter', 'Tangent', 'Secant'], answer: 1,
    solution: ['A chord joins two points on the circle. It may miss the center.', 'A tangent touches the circle once. A secant cuts it twice. Neither needs to pass through the center.', 'A diameter is a chord through the center, by definition.'] },
  { id: 'c8-1-3', chapter: 'ch8', section: '8-1', set: 'check', type: 'numeric', prompt: 'Line $PT$ is tangent to circle $O$ at $T$. $OT = 5$ and $PT = 12$. Find $OP$.', answer: 13, tolerance: 0.5,
    solution: ['The radius $\\overline{OT}$ is perpendicular to the tangent at $T$ (Theorem 8.16).', 'Triangle $OTP$ is a right triangle with legs $5$ and $12$.', '$OP^2 = 5^2 + 12^2 = 169$, so $OP = 13$.'] },
  { id: 'c8-2-1', chapter: 'ch8', section: '8-2', set: 'check', type: 'diagram', figure: { kind: 'inscribed', arc: 70 }, prompt: 'Central angle $\\angle AOC$ measures $70^\\circ$. Find $m\\widehat{AC}$.', answer: 70, tolerance: 0.5, unit: '°',
    solution: ['Use the Central Angle Theorem (Theorem 8.2).', 'The minor arc equals its central angle.', '$m\\widehat{AC} = 70^\\circ$'] },
  { id: 'c8-2-2', chapter: 'ch8', section: '8-2', set: 'check', type: 'numeric', prompt: 'Minor arc $AB$ measures $135^\\circ$. Point $C$ is on the major arc. Find $m\\widehat{ACB}$.', answer: 225, tolerance: 0.5, unit: '°',
    solution: ['The minor arc and the major arc make the whole circle.', '$m\\widehat{ACB} = 360^\\circ - 135^\\circ = 225^\\circ$'] },
  { id: 'c8-2-3', chapter: 'ch8', section: '8-2', set: 'check', type: 'mc', prompt: 'Points $A$, $B$, and $C$ are on a circle. Which name is correct for the major arc from $A$ to $B$ that passes through $C$?', choices: ['$\\widehat{AB}$', '$\\widehat{ACB}$', '$\\angle ACB$', '$\\overline{AB}$'], answer: 1,
    solution: ['A major arc needs three letters. The middle letter is a point on the arc.', '$\\widehat{AB}$ names the minor arc. $\\angle ACB$ is an angle. $\\overline{AB}$ is a chord.', 'The major arc is $\\widehat{ACB}$.'] },
  { id: 'c8-3-1', chapter: 'ch8', section: '8-3', set: 'check', type: 'numeric', prompt: 'Points $A$, $B$, and $C$ cut a circle into three arcs. $m\\widehat{AB} = 100^\\circ$ and $m\\widehat{BC} = 140^\\circ$. Find $m\\widehat{CA}$.', answer: 120, tolerance: 0.5, unit: '°',
    solution: ['The three arcs make the whole circle, so they add to $360^\\circ$.', '$m\\widehat{CA} = 360^\\circ - 100^\\circ - 140^\\circ = 120^\\circ$'] },
  { id: 'c8-3-2', chapter: 'ch8', section: '8-3', set: 'check', type: 'numeric', prompt: 'In circle $O$, central angles $\\angle AOB$ and $\\angle BOC$ are congruent. $m\\widehat{ABC} = 150^\\circ$. Find $m\\widehat{AB}$.', answer: 75, tolerance: 0.5, unit: '°',
    solution: ['Congruent central angles cut off congruent arcs (Theorem 8.3), so $m\\widehat{AB} = m\\widehat{BC}$.', 'By the Arc Addition Postulate, $m\\widehat{AB} + m\\widehat{BC} = 150^\\circ$.', '$2 \\cdot m\\widehat{AB} = 150^\\circ$, so $m\\widehat{AB} = 75^\\circ$.'] },
  { id: 'c8-3-3', chapter: 'ch8', section: '8-3', set: 'check', type: 'mc', prompt: '$\\overline{PQ}$ is a diameter of circle $O$. Point $R$ is on the circle. $m\\widehat{PR} = 65^\\circ$. Find $m\\widehat{RQ}$.', choices: ['$65^\\circ$', '$115^\\circ$', '$130^\\circ$', '$295^\\circ$'], answer: 1,
    solution: ['A diameter makes a semicircle of $180^\\circ$ (Theorem 8.4).', 'Use the Arc Addition Postulate: $m\\widehat{PR} + m\\widehat{RQ} = 180^\\circ$.', '$m\\widehat{RQ} = 180^\\circ - 65^\\circ = 115^\\circ$'] },
  { id: 'c8-5-1', chapter: 'ch8', section: '8-5', set: 'check', type: 'numeric', prompt: 'Two chords cross inside a circle. The angle between them intercepts arcs of $50^\\circ$ and $120^\\circ$. Find the angle.', answer: 85, tolerance: 0.5, unit: '°',
    solution: ['Use the Chord-Chord Angle Theorem (Theorem 8.9).', 'The angle is half the sum of the two arcs.', '$\\tfrac{1}{2}(50^\\circ + 120^\\circ) = 85^\\circ$'] },
  { id: 'c8-5-2', chapter: 'ch8', section: '8-5', set: 'check', type: 'numeric', prompt: 'Two tangents from point $P$ touch a circle. They cut the circle into arcs of $230^\\circ$ and $130^\\circ$. Find $m\\angle P$.', answer: 50, tolerance: 0.5, unit: '°',
    solution: ['The vertex is outside the circle. The angle is half the difference of the far arc and the near arc.', '$m\\angle P = \\tfrac{1}{2}(230^\\circ - 130^\\circ) = 50^\\circ$'] },
  { id: 'c8-5-3', chapter: 'ch8', section: '8-5', set: 'check', type: 'mc', prompt: 'A tangent and a chord meet at a point on the circle. The arc inside the angle measures $140^\\circ$. Find the angle.', choices: ['$35^\\circ$', '$70^\\circ$', '$140^\\circ$', '$220^\\circ$'], answer: 1,
    solution: ['Use the Tangent-Chord Angle Theorem (Theorem 8.17).', 'The angle is half the arc inside it.', '$\\tfrac{1}{2}(140^\\circ) = 70^\\circ$'] },
  { id: 'c8-6-1', chapter: 'ch8', section: '8-6', set: 'check', type: 'diagram', figure: { kind: 'circle', r: 10 }, prompt: 'Circle $O$ has radius $10$. A diameter is perpendicular to chord $\\overline{AB}$ at $M$. $AB = 16$. Find $OM$.', answer: 6, tolerance: 0.5,
    solution: ['The diameter bisects the chord (Theorem 8.11), so $AM = 8$.', 'Triangle $OMA$ has a right angle at $M$ and hypotenuse $OA = 10$.', '$OM^2 = 10^2 - 8^2 = 36$, so $OM = 6$.'] },
  { id: 'c8-6-2', chapter: 'ch8', section: '8-6', set: 'check', type: 'numeric', prompt: 'In circle $O$, $\\overline{AB} \\cong \\overline{CD}$. $m\\widehat{CD} = 84^\\circ$. Find $m\\widehat{AB}$.', answer: 84, tolerance: 0.5, unit: '°',
    solution: ['Congruent chords cut off congruent arcs (Theorem 8.18).', '$m\\widehat{AB} = m\\widehat{CD} = 84^\\circ$'] },
  { id: 'c8-6-3', chapter: 'ch8', section: '8-6', set: 'check', type: 'mc', prompt: 'Chords $\\overline{PQ}$ and $\\overline{RS}$ are each $6$ units from the center of the same circle. $PQ = 14$. Find $RS$.', choices: ['7', '12', '14', '28'], answer: 2,
    solution: ['Chords at the same distance from the center are congruent (Theorem 8.19).', '$RS = PQ = 14$'] },
  { id: 'c8-7-1', chapter: 'ch8', section: '8-7', set: 'check', type: 'numeric', prompt: 'Chords $\\overline{AB}$ and $\\overline{CD}$ cross at $E$. $AE = 5$, $EB = 6$, and $CE = 3$. Find $ED$.', answer: 10, tolerance: 0.05,
    solution: ['Use Theorem 8.12: $AE \\cdot EB = CE \\cdot ED$.', '$5 \\cdot 6 = 3 \\cdot ED$', '$30 = 3 \\cdot ED$, so $ED = 10$.'] },
  { id: 'c8-7-2', chapter: 'ch8', section: '8-7', set: 'check', type: 'numeric', prompt: 'Two secants start at point $P$ outside a circle. The first has external segment $4$ and whole length $12$. The second has external segment $6$. Find its whole length.', answer: 8, tolerance: 0.05,
    solution: ['Use Theorem 8.20: whole times external is equal for both secants.', '$12 \\cdot 4 = x \\cdot 6$', '$48 = 6x$, so $x = 8$.'] },
  { id: 'c8-7-3', chapter: 'ch8', section: '8-7', set: 'check', type: 'mc', prompt: 'From point $P$, a tangent touches a circle at $T$. A secant from $P$ has external segment $4$ and whole length $16$. Find $PT$.', choices: ['4', '8', '12', '64'], answer: 1,
    solution: ['Use Theorem 8.13: $PT^2 = \\text{whole} \\cdot \\text{external}$.', '$PT^2 = 16 \\cdot 4 = 64$', '$PT = 8$'] },
  { id: 'c8-8-1', chapter: 'ch8', section: '8-8', set: 'check', type: 'diagram', figure: { kind: 'sector', r: 12, angle: 45 }, prompt: 'A circle has radius $12$. A central angle of $45^\\circ$ cuts off an arc. Find the arc length. Use $\\pi \\approx 3.14$.', answer: 9.42, tolerance: 0.05,
    solution: ['The fraction of the circle is $\\frac{45}{360} = \\frac{1}{8}$.', 'The circumference is $2\\pi r = 2(3.14)(12) = 75.36$.', 'Arc length $= \\tfrac{1}{8}(75.36) = 9.42$'] },
  { id: 'c8-8-2', chapter: 'ch8', section: '8-8', set: 'check', type: 'diagram', figure: { kind: 'sector', r: 4, angle: 90 }, prompt: 'A circle has radius $4$. A sector has a central angle of $90^\\circ$. Find the sector area. Use $\\pi \\approx 3.14$.', answer: 12.56, tolerance: 0.05, unit: 'units²',
    solution: ['The fraction of the circle is $\\frac{90}{360} = \\frac{1}{4}$.', 'The circle area is $\\pi r^2 = 3.14 \\cdot 16 = 50.24$.', 'Sector area $= \\tfrac{1}{4}(50.24) = 12.56$'] },
  { id: 'c8-8-3', chapter: 'ch8', section: '8-8', set: 'check', type: 'mc', prompt: 'A sector has a central angle of $120^\\circ$. What fraction of the whole circle area is the sector?', choices: ['$\\frac{1}{6}$', '$\\frac{1}{4}$', '$\\frac{1}{3}$', '$\\frac{1}{2}$'], answer: 2,
    solution: ['The fraction is the central angle over $360^\\circ$.', '$\\frac{120}{360} = \\frac{1}{3}$'] },
],

theorems: [
  { id: '8.1', chapter: 'ch8', kind: 'Postulate', name: 'Arc Addition Postulate', statement: 'If $B$ is on $\\widehat{AC}$, then $m\\widehat{AB} + m\\widehat{BC} = m\\widehat{AC}$.', section: '8-3' },
  { id: '8.2', chapter: 'ch8', kind: 'Theorem', name: 'Central Angle Theorem', statement: 'The measure of a minor arc equals the measure of its central angle.', section: '8-2' },
  { id: '8.3', chapter: 'ch8', kind: 'Theorem', name: 'Congruent Arcs', statement: 'In the same circle or in congruent circles, congruent central angles cut off congruent arcs.', section: '8-3' },
  { id: '8.4', chapter: 'ch8', kind: 'Theorem', name: 'Semicircle', statement: 'A diameter divides a circle into two arcs of $180^\\circ$ each.', section: '8-3' },
  { id: '8.5', chapter: 'ch8', kind: 'Theorem', name: 'Inscribed Angle Theorem', statement: 'The measure of an inscribed angle is half the measure of its intercepted arc.', section: '8-4' },
  { id: '8.6', chapter: 'ch8', kind: 'Theorem', name: 'Same Arc Corollary', statement: 'Inscribed angles that intercept the same arc are congruent.', section: '8-4' },
  { id: '8.7', chapter: 'ch8', kind: 'Theorem', name: 'Semicircle Corollary', statement: 'An angle inscribed in a semicircle is a right angle.', section: '8-4' },
  { id: '8.8', chapter: 'ch8', kind: 'Theorem', name: 'Inscribed Quadrilateral', statement: 'The opposite angles of an inscribed quadrilateral are supplementary.', section: '8-4' },
  { id: '8.9', chapter: 'ch8', kind: 'Theorem', name: 'Chord-Chord Angle', statement: 'The angle between two chords that cross inside a circle is half the sum of the intercepted arcs.', section: '8-5' },
  { id: '8.10', chapter: 'ch8', kind: 'Theorem', name: 'Secant-Secant Angle', statement: 'The angle between two secants from an outside point is half the difference of the intercepted arcs.', section: '8-5' },
  { id: '8.11', chapter: 'ch8', kind: 'Theorem', name: 'Perpendicular Diameter', statement: 'A diameter perpendicular to a chord bisects the chord and its arc.', section: '8-6' },
  { id: '8.12', chapter: 'ch8', kind: 'Theorem', name: 'Chord Segments', statement: 'If two chords cross inside a circle, the product of the segments of one chord equals the product of the segments of the other.', section: '8-7' },
  { id: '8.13', chapter: 'ch8', kind: 'Theorem', name: 'Tangent-Secant Segments', statement: 'From an outside point, the square of the tangent equals the product of the secant and its external segment.', section: '8-7' },
  { id: '8.14', chapter: 'ch8', kind: 'Theorem', name: 'Arc Length', statement: 'Arc length $= \\frac{\\theta}{360^\\circ} \\cdot 2\\pi r$.', section: '8-8' },
  { id: '8.15', chapter: 'ch8', kind: 'Theorem', name: 'Sector Area', statement: 'Sector area $= \\frac{\\theta}{360^\\circ} \\cdot \\pi r^2$.', section: '8-8' },
  { id: '8.16', chapter: 'ch8', kind: 'Theorem', name: 'Tangent-Radius Theorem', statement: 'A tangent is perpendicular to the radius drawn to the point of tangency.', section: '8-1' },
  { id: '8.17', chapter: 'ch8', kind: 'Theorem', name: 'Tangent-Chord Angle', statement: 'The angle between a tangent and a chord at the point of tangency is half the intercepted arc.', section: '8-5' },
  { id: '8.18', chapter: 'ch8', kind: 'Theorem', name: 'Congruent Chords', statement: 'In the same circle or in congruent circles, congruent chords cut off congruent arcs, and congruent arcs have congruent chords.', section: '8-6' },
  { id: '8.19', chapter: 'ch8', kind: 'Theorem', name: 'Equidistant Chords', statement: 'In the same circle or in congruent circles, two chords are congruent if and only if they are the same distance from the center.', section: '8-6' },
  { id: '8.20', chapter: 'ch8', kind: 'Theorem', name: 'Secant-Secant Segments', statement: 'From an outside point, the product of one whole secant and its external segment equals the same product for the other secant.', section: '8-7' },
],

glossary: [
  { term: 'Arc', def: 'A connected part of a circle.', section: '8-2' },
  { term: 'Central angle', def: 'An angle with its vertex at the center of a circle.', section: '8-2' },
  { term: 'Chord', def: 'A segment with both endpoints on a circle.', section: '8-1' },
  { term: 'Circumference', def: 'The distance around a circle, $C = 2\\pi r$.', section: '8-8' },
  { term: 'Diameter', def: 'A chord that passes through the center.', section: '8-1' },
  { term: 'Inscribed angle', def: 'An angle with its vertex on a circle and chords as sides.', section: '8-4' },
  { term: 'Intercepted arc', def: 'The arc inside an inscribed angle.', section: '8-4' },
  { term: 'Major arc', def: 'An arc greater than $180^\\circ$.', section: '8-2' },
  { term: 'Minor arc', def: 'An arc less than $180^\\circ$.', section: '8-2' },
  { term: 'Radius', def: 'A segment from the center to a point on the circle.', section: '8-1' },
  { term: 'Secant', def: 'A line that cuts a circle at two points.', section: '8-5' },
  { term: 'Sector', def: 'A region bounded by two radii and an arc.', section: '8-8' },
  { term: 'Semicircle', def: 'An arc of exactly $180^\\circ$.', section: '8-3' },
  { term: 'Tangent', def: 'A line that touches a circle at exactly one point.', section: '8-5' },
  { term: 'Point of tangency', def: 'The one point where a tangent touches a circle.', section: '8-1' },
  { term: 'Concentric circles', def: 'Circles in the same plane with the same center.', section: '8-1' },
  { term: 'Congruent circles', def: 'Circles with congruent radii.', section: '8-1' },
  { term: 'External segment', def: 'The part of a secant from an outside point to the near point on the circle.', section: '8-7' },
  { term: 'Arc length', def: 'The distance along an arc, a fraction of the circumference.', section: '8-8' },
],
};
