// Postulates and theorems. `section` links back to the lesson that uses it.
import type { Theorem, GlossaryEntry } from './types';

export const theorems: Theorem[] = [
  { id: '8.1', chapter: 'ch8', kind: 'Postulate', name: 'Arc Addition Postulate', statement: 'If $B$ is on $\\widehat{AC}$, then $m\\widehat{AB} + m\\widehat{BC} = m\\widehat{AC}$.', section: '8-3' },
  { id: '8.2', chapter: 'ch8', kind: 'Theorem', name: 'Central Angle Theorem', statement: 'The measure of a minor arc equals the measure of its central angle.', section: '8-2' },
  { id: '8.3', chapter: 'ch8', kind: 'Theorem', name: 'Congruent Arcs', statement: 'In the same circle or in congruent circles, congruent central angles cut off congruent arcs.', section: '8-3' },
  { id: '8.4', chapter: 'ch8', kind: 'Theorem', name: 'Semicircle', statement: 'A diameter divides a circle into two arcs of $180^\\circ$ each.', section: '8-3' },
  { id: '8.5', chapter: 'ch8', kind: 'Theorem', name: 'Inscribed Angle Theorem', statement: 'The measure of an inscribed angle is half the measure of its intercepted arc.', section: '8-4' },
  { id: '8.6', chapter: 'ch8', kind: 'Theorem', name: 'Same Arc Corollary', statement: 'Inscribed angles that intercept the same arc are congruent.', section: '8-4' },
  { id: '8.7', chapter: 'ch8', kind: 'Theorem', name: 'Semicircle Corollary', statement: 'An angle inscribed in a semicircle is a right angle.', section: '8-4' },
  { id: '8.8', chapter: 'ch8', kind: 'Theorem', name: 'Inscribed Quadrilateral', statement: 'The opposite angles of an inscribed quadrilateral are supplementary.', section: '8-4' },
  { id: '8.9', chapter: 'ch8', kind: 'Theorem', name: 'Chord-Chord Angle', statement: 'The angle between two chords that cross inside a circle is half the sum of the intercepted arcs.', section: '8-5' },
  { id: '8.10', chapter: 'ch8', kind: 'Theorem', name: 'Secant-Secant Angle', statement: 'The angle between two secants from an outside point is half the difference of the intercepted arcs.', section: '8-5' },
  { id: '8.11', chapter: 'ch8', kind: 'Theorem', name: 'Perpendicular Diameter', statement: 'A diameter perpendicular to a chord bisects the chord and its arc.', section: '8-6' },
  { id: '8.12', chapter: 'ch8', kind: 'Theorem', name: 'Chord Segments', statement: 'If two chords cross inside a circle, the product of the segments of one chord equals the product of the segments of the other.', section: '8-7' },
  { id: '8.13', chapter: 'ch8', kind: 'Theorem', name: 'Tangent-Secant Segments', statement: 'From an outside point, the square of the tangent equals the product of the secant and its external segment.', section: '8-7' },
  { id: '8.14', chapter: 'ch8', kind: 'Theorem', name: 'Arc Length', statement: 'Arc length $= \\frac{\\theta}{360^\\circ} \\cdot 2\\pi r$.', section: '8-8' },
  { id: '8.15', chapter: 'ch8', kind: 'Theorem', name: 'Sector Area', statement: 'Sector area $= \\frac{\\theta}{360^\\circ} \\cdot \\pi r^2$.', section: '8-8' },

  { id: '9.1', chapter: 'ch9', kind: 'Theorem', name: 'Volume of a Prism', statement: 'The volume of a prism is the base area times the height: $V = Bh$.', section: '9-1' },
  { id: '9.2', chapter: 'ch9', kind: 'Theorem', name: 'Lateral Area of a Right Prism', statement: 'The lateral area of a right prism is the base perimeter times the height: $LA = ph$.', section: '9-1' },
  { id: '9.3', chapter: 'ch9', kind: 'Postulate', name: "Cavalieri's Principle", statement: 'Two solids with equal heights and equal cross-sectional areas at every level have equal volumes.', section: '9-1' },
  { id: '9.4', chapter: 'ch9', kind: 'Theorem', name: 'Volume of a Cylinder', statement: '$V = \\pi r^2 h$ and $LA = 2\\pi r h$.', section: '9-2' },
  { id: '9.5', chapter: 'ch9', kind: 'Theorem', name: 'Volume of a Pyramid', statement: '$V = \\tfrac{1}{3} B h$.', section: '9-3' },
  { id: '9.6', chapter: 'ch9', kind: 'Theorem', name: 'Volume of a Cone', statement: '$V = \\tfrac{1}{3}\\pi r^2 h$ and $LA = \\pi r \\ell$.', section: '9-4' },
  { id: '9.7', chapter: 'ch9', kind: 'Theorem', name: 'Sphere', statement: '$V = \\tfrac{4}{3}\\pi r^3$ and $SA = 4\\pi r^2$.', section: '9-5' },

  { id: '10.1', chapter: 'ch10', kind: 'Theorem', name: 'Pythagorean Theorem', statement: 'In a right triangle, $a^2 + b^2 = c^2$.', section: '10-2' },
  { id: '10.2', chapter: 'ch10', kind: 'Theorem', name: 'Distance Formula', statement: '$d = \\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}$.', section: '10-2' },
  { id: '10.3', chapter: 'ch10', kind: 'Theorem', name: 'Midpoint Formula', statement: '$M = \\left(\\frac{x_1 + x_2}{2}, \\frac{y_1 + y_2}{2}\\right)$.', section: '10-3' },
  { id: '10.4', chapter: 'ch10', kind: 'Theorem', name: 'Slope Formula', statement: '$m = \\frac{y_2 - y_1}{x_2 - x_1}$, with $x_1 \\ne x_2$.', section: '10-4' },
  { id: '10.5', chapter: 'ch10', kind: 'Postulate', name: 'Parallel Slopes', statement: 'Two nonvertical lines are parallel if and only if they have equal slopes.', section: '10-5' },
  { id: '10.6', chapter: 'ch10', kind: 'Postulate', name: 'Perpendicular Slopes', statement: 'Two nonvertical lines are perpendicular if and only if the product of their slopes is $-1$.', section: '10-5' },
];

export const glossary: GlossaryEntry[] = [
  { term: 'Arc', def: 'A connected part of a circle.', section: '8-2' },
  { term: 'Central angle', def: 'An angle with its vertex at the center of a circle.', section: '8-2' },
  { term: 'Chord', def: 'A segment with both endpoints on a circle.', section: '8-1' },
  { term: 'Circumference', def: 'The distance around a circle, $C = 2\\pi r$.', section: '8-8' },
  { term: 'Diameter', def: 'A chord that passes through the center.', section: '8-1' },
  { term: 'Inscribed angle', def: 'An angle with its vertex on a circle and chords as sides.', section: '8-4' },
  { term: 'Intercepted arc', def: 'The arc inside an inscribed angle.', section: '8-4' },
  { term: 'Major arc', def: 'An arc greater than $180^\\circ$.', section: '8-2' },
  { term: 'Minor arc', def: 'An arc less than $180^\\circ$.', section: '8-2' },
  { term: 'Radius', def: 'A segment from the center to a point on the circle.', section: '8-1' },
  { term: 'Secant', def: 'A line that cuts a circle at two points.', section: '8-5' },
  { term: 'Sector', def: 'A region bounded by two radii and an arc.', section: '8-8' },
  { term: 'Semicircle', def: 'An arc of exactly $180^\\circ$.', section: '8-3' },
  { term: 'Tangent', def: 'A line that touches a circle at exactly one point.', section: '8-5' },
  { term: 'Altitude (of a solid)', def: 'The perpendicular distance between the bases.', section: '9-1' },
  { term: 'Base', def: 'A face that defines the shape of a solid.', section: '9-1' },
  { term: 'Cone', def: 'A solid with a circular base and one apex.', section: '9-4' },
  { term: 'Cylinder', def: 'A solid with two congruent circular bases.', section: '9-2' },
  { term: 'Lateral area', def: 'The area of all faces that are not bases.', section: '9-1' },
  { term: 'Oblique prism', def: 'A prism whose lateral edges are not perpendicular to the bases.', section: '9-1' },
  { term: 'Prism', def: 'A solid with two congruent parallel bases and parallelogram lateral faces.', section: '9-1' },
  { term: 'Pyramid', def: 'A solid with one base and triangular lateral faces that meet at an apex.', section: '9-3' },
  { term: 'Right prism', def: 'A prism whose lateral edges are perpendicular to the bases.', section: '9-1' },
  { term: 'Slant height', def: 'The distance from the apex to the edge of the base along a face.', section: '9-4' },
  { term: 'Sphere', def: 'All points in space at one distance from a center.', section: '9-5' },
  { term: 'Volume', def: 'The amount of space inside a solid.', section: '9-1' },
  { term: 'Coordinate plane', def: 'A plane with two perpendicular number lines.', section: '10-1' },
  { term: 'Distance formula', def: '$d = \\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}$.', section: '10-2' },
  { term: 'Midpoint', def: 'The point halfway between two points.', section: '10-3' },
  { term: 'Ordered pair', def: 'Two numbers $(x, y)$ that locate a point.', section: '10-1' },
  { term: 'Origin', def: 'The point $(0, 0)$.', section: '10-1' },
  { term: 'Quadrant', def: 'One of the four regions of the coordinate plane.', section: '10-1' },
  { term: 'Slope', def: 'Rise over run, $\\frac{\\Delta y}{\\Delta x}$.', section: '10-4' },
  { term: 'Slope-intercept form', def: '$y = mx + b$.', section: '10-6' },
  { term: 'Standard form', def: '$Ax + By = C$.', section: '10-6' },
  { term: 'Point-slope form', def: '$y - y_1 = m(x - x_1)$.', section: '10-6' },
  { term: 'y-intercept', def: 'The point where a line crosses the $y$-axis.', section: '10-6' },
];
